name: Unit tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        uses: jamie-pate/run-gut-tests-action@v2.0.3
        with:
          directory: .
          godotFlags: --headless
          gutConfigPath: .gutconfig.json
