name: Unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: jamie-pate/run-gut-tests-action@v2.0.3
        with:
          directory: .
          godotFlags: --headless
          gutConfigPath: .gutconfig.json
